curl -X POST -d '
{
      "issue": {
        "self": "https://jira.lzd.co/rest/api/2/issue/249781",
        "id": "249781",
        "fields": {
          "issuelinks": [],
          "customfield_16013": "null",
          "votes": {
            "hasVoted": "false",
            "self": "https://jira.lzd.co/rest/api/2/issue/MT-1035/votes",
            "votes": "0"
          },
          "customfield_16012": "null",
          "customfield_16011": "null",
          "customfield_16016": "null",
          "timetracking": {},
          "customfield_16015": "null",
          "customfield_16014": "null",
          "customfield_11200": "null",
          "customfield_13500": "null",
          "customfield_15800": "null",
          "resolution": "null",
          "customfield_12410": "null",
          "customfield_15801": "null",
          "customfield_13502": "null",
          "customfield_13501": "null",
          "customfield_12800": "null",
          "customfield_12404": "null",
          "customfield_12403": "null",
          "customfield_12802": "null",
          "customfield_12406": "null",
          "customfield_12801": "null",
          "customfield_12405": "null",
          "customfield_12804": "null",
          "customfield_12408": "null",
          "customfield_12407": "null",
          "customfield_12806": "null",
          "customfield_12409": "null",
          "customfield_12808": "null",
          "customfield_12807": "null",
          "customfield_12809": "null",
          "lastViewed": "null",
          "worklog": {
            "total": "0",
            "maxResults": "20",
            "worklogs": [],
            "startAt": "0"
          },
          "customfield_16001": "null",
          "customfield_16006": "null",
          "customfield_16005": "null",
          "logTruncated": "75/439 items shown",
          "customfield_16004": "null",
          "customfield_16003": "null",
          "customfield_10100": "null",
          "status": {
            "statusCategory": {
              "colorName": "blue-gray",
              "name": "To Do",
              "self": "https://jira.lzd.co/rest/api/2/statuscategory/2",
              "id": "2",
              "key": "new"
            },
            "name": "Open",
            "self": "https://jira.lzd.co/rest/api/2/status/1",
            "description": "The issue is open and ready for the assignee to start work on it.",
            "iconUrl": "https://jira.lzd.co/images/icons/statuses/open.png",
            "id": "1"
          },
          "customfield_12402": "null",
          "customfield_16007": "null",
          "customfield_12401": "null",
          "customfield_13724": "null",
          "customfield_15903": "null",
          "customfield_15904": "null",
          "customfield_11900": "null",
          "customfield_11305": "null",
          "customfield_12637": "null",
          "customfield_13726": "null",
          "customfield_13725": "null",
          "customfield_15902": "null",
          "aggregatetimeoriginalestimate": "null",
          "customfield_15907": "null",
          "timeestimate": "null",
          "customfield_12638": "null",
          "customfield_13727": "null",
          "customfield_15908": "null",
          "customfield_15905": "null",
          "customfield_15906": "null",
          "issuetype": {
            "avatarId": "17002",
            "name": "Maintenance",
            "self": "https://jira.lzd.co/rest/api/2/issuetype/13402",
            "description": "Maintenance period registration",
            "id": "13402",
            "iconUrl": "https://jira.lzd.co/secure/viewavatar?size=xsmall&avatarId=17002&avatarType=issuetype",
            "subtask": "false"
          },
          "subtasks": [],
          "customfield_12510": "null",
          "customfield_12631": "null",
          "customfield_13720": "null",
          "customfield_10602": "null",
          "customfield_12900": "null",
          "customfield_10800": "null",
          "customfield_15900": {
            "self": "https://jira.lzd.co/rest/api/2/customFieldOption/14300",
            "id": "14300",
            "value": "Planned Order"
          },
          "customfield_16100": "<div id=\"adminMessages\" class=\"warningBox\"><p>Are you sure you want to integrate manually? This action is for Release automation!</p></div>",
          "customfield_11801": "null",
          "customfield_11802": "null",
          "duedate": "null",
          "assignee": {
            "emailAddress": "oliver.nadj@lazada.com",
            "displayName": "oliver nadj",
            "name": "oliver.nadj",
            "self": "https://jira.lzd.co/rest/api/2/user?username=oliver.nadj",
            "active": "true",
            "timeZone": "Asia/Ho_Chi_Minh",
            "avatarUrls": {
              "48x48": "https://jira.lzd.co/secure/useravatar?ownerId=oliver.nadj&avatarId=18533",
              "24x24": "https://jira.lzd.co/secure/useravatar?size=small&ownerId=oliver.nadj&avatarId=18533",
              "16x16": "https://jira.lzd.co/secure/useravatar?size=xsmall&ownerId=oliver.nadj&avatarId=18533",
              "32x32": "https://jira.lzd.co/secure/useravatar?size=medium&ownerId=oliver.nadj&avatarId=18533"
            },
            "key": "oliver.nadj"
          }
        },
        "key": "MT-1035"
      },
      "issue_event_type_name": "issue_created",
      "webhookEvent": "jira:issue_created",
      "user": {
        "emailAddress": "hien.nguyen@lazada.com",
        "displayName": "911. Hien Nguyen",
        "name": "hien_nguyen",
        "self": "https://jira.lzd.co/rest/api/2/user?username=hien_nguyen",
        "active": "true",
        "timeZone": "Asia/Ho_Chi_Minh",
        "avatarUrls": {
          "48x48": "https://jira.lzd.co/secure/useravatar?ownerId=hien_nguyen&avatarId=17125",
          "24x24": "https://jira.lzd.co/secure/useravatar?size=small&ownerId=hien_nguyen&avatarId=17125",
          "16x16": "https://jira.lzd.co/secure/useravatar?size=xsmall&ownerId=hien_nguyen&avatarId=17125",
          "32x32": "https://jira.lzd.co/secure/useravatar?size=medium&ownerId=hien_nguyen&avatarId=17125"
        },
        "key": "hien_nguyen"
      },
      "timestamp": "1502795464619"
    }
' http://localhost:8383/maintenance